### ISSUE TITLE
Failed to find skin data

### ISSUE THREAD

**Issue by Incluuu** [SkinsRestorer/SkinsRestorerX#1985]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Are you using forge/fabric/any modloader?

No

### Installed conforming to our guide?

- [x] I have read the installation guide and performed all steps

### Describe your issue

I can't change skins

### How can we reproduce what you got?

1. /skin 42JoJo
2. errors

### Server/Error Logs

https://gist.github.com/Incluuu/319aec35599b5910a3b33ab4be1396bb
https://gist.github.com/Incluuu/f246776aaacb5f5ff51673c268633a40

### Minecraft implementation

```markdown
- Proxy: Velocity
- Backend: Paper 1.21.5
```

### What client are you using?

1.21.7

### SkinsRestorer Version

15.7.4

### List of plugins

Velocity Plugins like: SkinsRestorer, MiniMotd

### Java Version

java 21

### Does your issue require a plugin in order to reproduce?

None

**Comment by xknat** [comment]
Our api was having hiccup. I restarted it and it should now be resolved

**Comment by Incluuu** [comment]
> Our api was having hiccup. I restarted it and it should now be resolved

Still errors

<img width="422" height="41" alt="Image" src="https://github.com/user-attachments/assets/52821e26-fe03-46fe-ae91-f2b2ac9a973c" />

[19:00:59] [ForkJoinPool.commonPool-worker-8/WARN] [skinsrestorer]: An unexpected error occurred while executing a command
[19:01:32] [ForkJoinPool.commonPool-worker-3/WARN] [skinsrestorer]: An unexpected error occurred while executing a command
[19:05:20] [ForkJoinPool.commonPool-worker-1/WARN] [skinsrestorer]: An unexpected error occurred while executing a command
[19:05:29] [ForkJoinPool.commonPool-worker-3/WARN] [skinsrestorer]: An unexpected error occurred while executing a command
[19:05:49] [ForkJoinPool.commonPool-worker-1/WARN] [skinsrestorer]: An unexpected error occurred while executing a command
[19:05:59] [ForkJoinPool.commonPool-worker-1/WARN] [skinsrestorer]: An unexpected error occurred while executing a command
[19:09:48] [ForkJoinPool.commonPool-worker-10/WARN] [skinsrestorer]: An unexpected error occurred while executing a command
[19:14:32] [ForkJoinPool.commonPool-worker-1/WARN] [skinsrestorer]: An unexpected error occurred while executing a command
[19:14:39] [ForkJoinPool.commonPool-worker-7/WARN] [skinsrestorer]: An unexpected error occurred while executing a command
[19:23:51] [ForkJoinPool.commonPool-worker-1/WARN] [skinsrestorer]: An unexpected error occurred while executing a command
[19:32:22] [ForkJoinPool.commonPool-worker-1/WARN] [skinsrestorer]: An unexpected error occurred while executing a command
[19:32:45] [ForkJoinPool.commonPool-worker-7/WARN] [skinsrestorer]: An unexpected error occurred while executing a command
[19:32:52] [ForkJoinPool.commonPool-worker-3/WARN] [skinsrestorer]: An unexpected error occurred while executing a command
[19:33:24] [ForkJoinPool.commonPool-worker-4/WARN] [skinsrestorer]: An unexpected error occurred while executing a command
[19:33:28] [ForkJoinPool.commonPool-worker-1/WARN] [skinsrestorer]: An unexpected error occurred while executing a command
[19:33:50] [ForkJoinPool.commonPool-worker-4/WARN] [skinsrestorer]: An unexpected error occurred while executing a command
[19:34:39] [ForkJoinPool.commonPool-worker-8/WARN] [skinsrestorer]: An unexpected error occurred while executing a command
[19:35:45] [ForkJoinPool.commonPool-worker-1/WARN] [skinsrestorer]: An unexpected error occurred while executing a command
[19:35:54] [ForkJoinPool.commonPool-worker-7/WARN] [skinsrestorer]: An unexpected error occurred while executing a command
[19:35:56] [ForkJoinPool.commonPool-worker-1/WARN] [skinsrestorer]: An unexpected error occurred while executing a command
[19:43:34] [ForkJoinPool.commonPool-worker-1/WARN] [skinsrestorer]: An unexpected error occurred while executing a command
[19:47:37] [ForkJoinPool.commonPool-worker-7/WARN] [skinsrestorer]: An unexpected error occurred while executing a command
[19:47:44] [ForkJoinPool.commonPool-worker-4/WARN] [skinsrestorer]: An unexpected error occurred while executing a command
[19:47:52] [ForkJoinPool.commonPool-worker-1/WARN] [skinsrestorer]: An unexpected error occurred while executing a command
[19:47:59] [ForkJoinPool.commonPool-worker-4/WARN] [skinsrestorer]: An unexpected error occurred while executing a command


net.skinsrestorer.shared.exception.DataRequestExceptionShared: Failed to get UUID for player: pablo_pika
	at net.skinsrestorer.shared.connections.MojangAPIImpl.getUUID(MojangAPIImpl.java:99) ~[?:?]
	at net.skinsrestorer.shared.connections.MojangAPIImpl.getSkin(MojangAPIImpl.java:66) ~[?:?]
	at net.skinsrestorer.shared.storage.SkinStorageImpl.getPlayerSkin(SkinStorageImpl.java:161) ~[?:?]
	at net.skinsrestorer.shared.storage.SkinStorageImpl.findOrCreateSkinData(SkinStorageImpl.java:333) ~[?:?]
	at net.skinsrestorer.shared.commands.SkinCommand.setSkin(SkinCommand.java:539) ~[?:?]
	at net.skinsrestorer.shared.commands.SkinCommand.onSkinSetOther(SkinCommand.java:324) ~[?:?]
	at net.skinsrestorer.shared.commands.SkinCommand.onSkinSetShort(SkinCommand.java:162) ~[?:?]
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733) ~[?:?]
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:758) ~[?:?]
	at net.skinsrestorer.shadow.cloud.annotations.MethodCommandExecutionHandler.executeFuture(MethodCommandExecutionHandler.java:88) ~[?:?]
	at net.skinsrestorer.shadow.cloud.execution.ExecutionCoordinatorImpl.lambda$coordinateExecution$4(ExecutionCoordinatorImpl.java:121) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]

**Comment by xknat** [comment]
Thanks, looking into it

**Comment by Incluuu** [comment]
Still happening, I pasted a few snippets

> Thanks, looking into it

[10:25:38] [ForkJoinPool.commonPool-worker-1/WARN] [skinsrestorer]: Failed to find skin data
[10:25:57] [ForkJoinPool.commonPool-worker-1/WARN] [skinsrestorer]: Failed to find skin data

[12:33:35] [ForkJoinPool.commonPool-worker-3/WARN] [skinsrestorer]: Failed to find skin data for
[12:33:38] [ForkJoinPool.commonPool-worker-3/WARN] [skinsrestorer]: Failed to find skin data for

[14:28:42] [ForkJoinPool.commonPool-worker-7/WARN] [skinsrestorer]: Failed to find skin data for
[14:29:15] [ForkJoinPool.commonPool-worker-7/WARN] [skinsrestorer]: Failed to find skin data for
[14:29:30] [ForkJoinPool.commonPool-worker-7/WARN] [skinsrestorer]: Failed to find skin data for
[14:29:42] [ForkJoinPool.commonPool-worker-7/WARN] [skinsrestorer]: Failed to find skin data for
[14:30:42] [ForkJoinPool.commonPool-worker-7/WARN] [skinsrestorer]: Failed to find skin data for
[14:32:52] [ForkJoinPool.commonPool-worker-7/WARN] [skinsrestorer]: Failed to find skin data for
[14:32:56] [ForkJoinPool.commonPool-worker-7/WARN] [skinsrestorer]: Failed to find skin data for

**Comment by xknat** [comment]
We are going to migrate our existing eclipse (sr mojangapi) to another framework

**Comment by Incluuu** [comment]
> We are going to migrate our existing eclipse (sr mojangapi) to another framework

I used SkinsRestorer version: 15.7.7-SNAPSHOT and I still receive errors:

[11:02:57] [ForkJoinPool.commonPool-worker-4/WARN] [skinsrestorer]: Failed to find skin data for StormByte
[11:06:29] [ForkJoinPool.commonPool-worker-4/WARN] [skinsrestorer]: Failed to find skin data for CloudNova
[11:06:37] [ForkJoinPool.commonPool-worker-4/WARN] [skinsrestorer]: Failed to find skin data for CloudNova
[11:06:45] [ForkJoinPool.commonPool-worker-8/WARN] [skinsrestorer]: Failed to find skin data for FrostPixel
[11:06:55] [ForkJoinPool.commonPool-worker-2/WARN] [skinsrestorer]: Failed to find skin data for FrostPixel
[11:34:40] [ForkJoinPool.commonPool-worker-1/WARN] [skinsrestorer]: Failed to find skin data for CreeperBox
[11:48:48] [ForkJoinPool.commonPool-worker-1/WARN] [skinsrestorer]: Failed to find skin data for LavaMage
[11:48:56] [ForkJoinPool.commonPool-worker-4/WARN] [skinsrestorer]: Failed to find skin data for LavaMage
[11:57:51] [ForkJoinPool.commonPool-worker-4/WARN] [skinsrestorer]: Failed to find skin data for SolarKnight
[12:23:43] [ForkJoinPool.commonPool-worker-8/WARN] [skinsrestorer]: Failed to find skin data for TechnoSpark
[12:29:54] [ForkJoinPool.commonPool-worker-8/WARN] [skinsrestorer]: Failed to find skin data for NeoCore
[12:41:44] [ForkJoinPool.commonPool-worker-4/WARN] [skinsrestorer]: Failed to find skin data for DogeMaster
[12:42:30] [ForkJoinPool.commonPool-worker-4/WARN] [skinsrestorer]: Failed to find skin data for ZenoDrift
[12:42:43] [ForkJoinPool.commonPool-worker-4/WARN] [skinsrestorer]: Failed to find skin data for ZenoDrift
[12:42:53] [ForkJoinPool.commonPool-worker-4/WARN] [skinsrestorer]: Failed to find skin data for VoxelNova
[12:43:41] [ForkJoinPool.commonPool-worker-4/WARN] [skinsrestorer]: Failed to find skin data for FoxBit
[12:43:47] [ForkJoinPool.commonPool-worker-3/WARN] [skinsrestorer]: Failed to find skin data for FoxBit
[12:48:39] [ForkJoinPool.commonPool-worker-3/WARN] [skinsrestorer]: Failed to find skin data for CyberDawn
[12:49:44] [ForkJoinPool.commonPool-worker-4/WARN] [skinsrestorer]: Failed to find skin data for Glitchy
[12:49:47] [ForkJoinPool.commonPool-worker-8/WARN] [skinsrestorer]: Failed to find skin data for PixelX
[12:51:32] [ForkJoinPool.commonPool-worker-2/WARN] [skinsrestorer]: Failed to find skin data for EchoLite
[12:55:29] [ForkJoinPool.commonPool-worker-2/WARN] [skinsrestorer]: Failed to find skin data for AeroRunner
[12:55:45] [ForkJoinPool.commonPool-worker-8/WARN] [skinsrestorer]: Failed to find skin data for AeroRunner
[13:02:28] [ForkJoinPool.commonPool-worker-9/WARN] [skinsrestorer]: Failed to find skin data for BlazeZone
[13:02:47] [ForkJoinPool.commonPool-worker-8/WARN] [skinsrestorer]: Failed to find skin data for SirNova
[13:09:59] [ForkJoinPool.commonPool-worker-8/WARN] [skinsrestorer]: Failed to find skin data for GoldyYT
[13:10:38] [ForkJoinPool.commonPool-worker-6/WARN] [skinsrestorer]: Failed to find skin data for CubeSpark
[13:30:49] [ForkJoinPool.commonPool-worker-3/WARN] [skinsrestorer]: Failed to find skin data for ZenixYT
[13:30:58] [ForkJoinPool.commonPool-worker-9/WARN] [skinsrestorer]: Failed to find skin data for Zenixa
[13:35:43] [ForkJoinPool.commonPool-worker-6/WARN] [skinsrestorer]: Failed to find skin data for NetSky
[13:36:10] [ForkJoinPool.commonPool-worker-3/WARN] [skinsrestorer]: Failed to find skin data for NetSky
[13:36:27] [ForkJoinPool.commonPool-worker-3/WARN] [skinsrestorer]: Failed to find skin data for CharlesMC
[13:36:41] [ForkJoinPool.commonPool-worker-4/WARN] [skinsrestorer]: Failed to find skin data for CharlesMC
[13:36:49] [ForkJoinPool.commonPool-worker-6/WARN] [skinsrestorer]: Failed to find skin data for XZevik
[13:45:55] [ForkJoinPool.commonPool-worker-3/WARN] [skinsrestorer]: Failed to find skin data for Borynx
[13:47:25] [ForkJoinPool.commonPool-worker-9/WARN] [skinsrestorer]: Failed to find skin data for Shivern
[13:49:42] [ForkJoinPool.commonPool-worker-9/WARN] [skinsrestorer]: Failed to find skin data for PunZz
[13:49:55] [ForkJoinPool.commonPool-worker-9/WARN] [skinsrestorer]: Failed to find skin data for Ethereal
[13:50:39] [ForkJoinPool.commonPool-worker-9/WARN] [skinsrestorer]: Failed to find skin data for DupaKing
[13:50:45] [ForkJoinPool.commonPool-worker-9/WARN] [skinsrestorer]: Failed to find skin data for DupaKing
[13:51:41] [ForkJoinPool.commonPool-worker-8/WARN] [skinsrestorer]: Failed to find skin data for Maciozo
[13:51:50] [ForkJoinPool.commonPool-worker-9/WARN] [skinsrestorer]: Failed to find skin data for Sasuna
[14:03:42] [ForkJoinPool.commonPool-worker-5/WARN] [skinsrestorer]: Failed to find skin data for Ralbyte
[14:14:29] [ForkJoinPool.commonPool-worker-4/WARN] [skinsrestorer]: Failed to find skin data for ZyroOne
[14:25:19] [ForkJoinPool.commonPool-worker-3/WARN] [skinsrestorer]: Failed to find skin data for VXyz_
[14:25:52] [ForkJoinPool.commonPool-worker-8/WARN] [skinsrestorer]: Failed to find skin data for VQZrox
[14:29:27] [ForkJoinPool.commonPool-worker-2/WARN] [skinsrestorer]: Failed to find skin data for SoulVoid
[14:29:54] [ForkJoinPool.commonPool-worker-2/WARN] [skinsrestorer]: Failed to find skin data for TopForever
[14:30:48] [ForkJoinPool.commonPool-worker-8/WARN] [skinsrestorer]: Failed to find skin data for SoulVoid

net.skinsrestorer.shared.exception.DataRequestExceptionShared: net.skinsrestorer.shared.exception.DataRequestExceptionShared: Failed to get UUID for player: NovaKnight
Caused by: net.skinsrestorer.shared.exception.DataRequestExceptionShared: Failed to get UUID for player: NovaKnight
net.skinsrestorer.shared.exception.DataRequestExceptionShared: Failed to get UUID for player: NovaKnight
net.skinsrestorer.shared.exception.DataRequestExceptionShared: net.skinsrestorer.shared.exception.DataRequestExceptionShared: Failed to get UUID for player: ZenTatsu


Full logs: https://gist.github.com/Incluuu/df32be3b76ce1f62591fb8ffc76b9edb

During these errors, players receive the normal error message (thanks for adding this)

**Comment by xknat** [comment]
We swapped back to the mojang one, this issue was there because we had a hickup on our eclipse.
I think these messages should now not appear any longer?

**Comment by Incluuu** [comment]
> We swapped back to the mojang one, this issue was there because we had a hickup on our eclipse. I think these messages should now not appear any longer?


I still receive errors, when: change skins, clear skins



[ForkJoinPool.commonPool-worker-9/WARN] [skinsrestorer]: Failed to find skin data for Barry
net.skinsrestorer.shared.exception.DataRequestExceptionShared: net.skinsrestorer.shared.exception.DataRequestExceptionShared: Failed to get UUID for player: Barry
	at net.skinsrestorer.shared.storage.CacheStorageImpl.getUUID(CacheStorageImpl.java:77) ~[?:?]
	at net.skinsrestorer.shared.storage.SkinStorageImpl.findSkinData(SkinStorageImpl.java:250) ~[?:?]
	at net.skinsrestorer.shared.storage.SkinStorageImpl.findOrCreateSkinData(SkinStorageImpl.java:307) ~[?:?]
	at net.skinsrestorer.shared.commands.SkinCommand.setSkin(SkinCommand.java:539) ~[?:?]
	at net.skinsrestorer.shared.commands.SkinCommand.onSkinSetOther(SkinCommand.java:324) ~[?:?]
	at net.skinsrestorer.shared.commands.SkinCommand.onSkinSetOther(SkinCommand.java:312) ~[?:?]
	at net.skinsrestorer.shared.commands.SkinCommand.onSkinSet(SkinCommand.java:304) ~[?:?]
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733) ~[?:?]
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:758) ~[?:?]
	at net.skinsrestorer.shadow.cloud.annotations.MethodCommandExecutionHandler.executeFuture(MethodCommandExecutionHandler.java:88) ~[?:?]
	at net.skinsrestorer.shadow.cloud.execution.ExecutionCoordinatorImpl.lambda$coordinateExecution$4(ExecutionCoordinatorImpl.java:121) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
Caused by: net.skinsrestorer.shared.exception.DataRequestExceptionShared: Failed to get UUID for player: Barry
	at net.skinsrestorer.shared.connections.MojangAPIImpl.getUUID(MojangAPIImpl.java:99) ~[?:?]
	at net.skinsrestorer.shared.storage.CacheStorageImpl.getUUID(CacheStorageImpl.java:68) ~[?:?]
	... 17 more
[ForkJoinPool.commonPool-worker-9/WARN] [skinsrestorer]: An unexpected error occurred while executing a command
net.skinsrestorer.shared.exception.DataRequestExceptionShared: Failed to get UUID for player: Barry
	at net.skinsrestorer.shared.connections.MojangAPIImpl.getUUID(MojangAPIImpl.java:99) ~[?:?]
	at net.skinsrestorer.shared.connections.MojangAPIImpl.getSkin(MojangAPIImpl.java:66) ~[?:?]
	at net.skinsrestorer.shared.storage.SkinStorageImpl.getPlayerSkin(SkinStorageImpl.java:161) ~[?:?]
	at net.skinsrestorer.shared.storage.SkinStorageImpl.findOrCreateSkinData(SkinStorageImpl.java:333) ~[?:?]
	at net.skinsrestorer.shared.commands.SkinCommand.setSkin(SkinCommand.java:539) ~[?:?]
	at net.skinsrestorer.shared.commands.SkinCommand.onSkinSetOther(SkinCommand.java:324) ~[?:?]
	at net.skinsrestorer.shared.commands.SkinCommand.onSkinSetOther(SkinCommand.java:312) ~[?:?]
	at net.skinsrestorer.shared.commands.SkinCommand.onSkinSet(SkinCommand.java:304) ~[?:?]
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733) ~[?:?]
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:758) ~[?:?]
	at net.skinsrestorer.shadow.cloud.annotations.MethodCommandExecutionHandler.executeFuture(MethodCommandExecutionHandler.java:88) ~[?:?]
	at net.skinsrestorer.shadow.cloud.execution.ExecutionCoordinatorImpl.lambda$coordinateExecution$4(ExecutionCoordinatorImpl.java:121) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]


[skinsrestorer]: Error while clearing skin
net.skinsrestorer.shared.exception.DataRequestExceptionShared: Failed to get UUID for player: catmennn
	at net.skinsrestorer.shared.connections.MojangAPIImpl.getUUID(MojangAPIImpl.java:99) ~[?:?]
	at net.skinsrestorer.shared.connections.MojangAPIImpl.getSkin(MojangAPIImpl.java:66) ~[?:?]
	at net.skinsrestorer.shared.storage.SkinStorageImpl.getPlayerSkin(SkinStorageImpl.java:161) ~[?:?]
	at net.skinsrestorer.shared.storage.SkinStorageImpl.getPlayerSkin(SkinStorageImpl.java:134) ~[?:?]
	at net.skinsrestorer.shared.storage.PlayerStorageImpl.getSkinForPlayerResult(PlayerStorageImpl.java:301) ~[?:?]
	at net.skinsrestorer.shared.storage.PlayerStorageImpl.getSkinForPlayer(PlayerStorageImpl.java:273) ~[?:?]
	at net.skinsrestorer.api.storage.PlayerStorage.getSkinForPlayer(PlayerStorage.java:97) ~[?:?]
	at net.skinsrestorer.shared.commands.SkinCommand.onSkinClearOther(SkinCommand.java:195) ~[?:?]
	at net.skinsrestorer.shared.commands.SkinCommand.onSkinClear(SkinCommand.java:178) ~[?:?]
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733) ~[?:?]
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:758) ~[?:?]
	at net.skinsrestorer.shadow.cloud.annotations.MethodCommandExecutionHandler.executeFuture(MethodCommandExecutionHandler.java:88) ~[?:?]
	at net.skinsrestorer.shadow.cloud.execution.ExecutionCoordinatorImpl.lambda$coordinateExecution$4(ExecutionCoordinatorImpl.java:121) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]

**Comment by xknat** [comment]
Ty, I'll look into it.
I will also move the stacktrace to debug because I think we have no real use for that
