### ISSUE TITLE
Incompatible with ProtocolSupport Edit: and also AntiAura AntiCheat

### ISSUE THREAD

**Issue by cmod31** [SkinsRestorer/SkinsRestorerX#604]
## Describe the bug
First there is [this issue](https://github.com/ProtocolSupport/ProtocolSupport/issues/1351) but it was closed because its an SkinRestorer incompatibility.
-Entitys don't move when i want to use ProtocolSupport on the same server with SR.
-Entitys are sometimes invisible but visible for some players.
-Sometimes just the entity/player model doesn't move but makes particles and sounds and is there
-Players get teleported to back where they started with the entity when they leave it
-Players can move but are invisible and the player model stands where the player logged in

## How can we reproduce what you got?
1. Install Protocolsupport with Skinrestorer
2. Play with other players and ride horses or do some other entity stuff
(i could do this with someone on my server for testing if interested)

**Expected behavior**
Compatibility with ProtocolSupport

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**

**What version? Do NOT answer LATEST**
* SkinsRestorer: v14.1.1
* Paper version: git-Paper-136 (MC: 1.17.1)
* No BungeeCord
* Java: 16
* plugin list:   AuthMe, BedrockPlayerManager, ClearLag, CoreProtect, DiscordSRV, FastLogin, floodgate, Geyser-Spigot, GSit, ImageMaps, InventoryRollback, InvSeePlusPlus, KeepDeathDrop, NekoC*, PlaceholderAPI, PlayerLeash, ProtocolLib, SkinsRestorer, Vault, Whitelist*
* MinecraftLauncher?: Normal Windows Minecraft Java Launcher (2.2.3965)
* Client Mods: Optifine

## Logs
Replace the links below by a paste of your startup logs (if you run a **Bungeecord** server, please send startup logs from **Bungeecord *AND* Spigot/Bukkit**)
https://gist.github.com/cmod31/34a8f593a4c18112a0f80f42a25d576a#file-gistfile1-txt
https://hastebin.com/ovojiyebux.makefile

## Additional context
Server is running in offlinemode.

**Comment by xknat** [comment]
@cmod31 can you confirm on latest dev build?

**Comment by cmod31** [comment]
What do you mean? I listed the versions there

**Comment by xknat** [comment]
> What do you mean? I listed the versions there

@cmod31 can you try from our dev branch? -> https://ci.codemc.io/job/SkinsRestorer/job/SkinsRestorerX-DEV/

**Comment by cmod31** [comment]
Tomorrow yeah

**Comment by cmod31** [comment]
ok i did it now already so you can close it if its actively fixed in the dev builds

**Comment by cmod31** [comment]
ok everything works fine for me thx

**Comment by cmod31** [comment]
Ok its still an issue but it doesn't acue that often anymore but i have to delete protocolsupport for now because server restarts don't fix this issue

**Comment by vaporvee** [comment]
Its still an issue is there something new about this? I really need protocol support

**Comment by vaporvee** [comment]
Now it has an similar issue with AntiAura. Entitys get invisible and are bugging. it could be fixed when this is fixed but when i remove skinrestorer it also runs just fine
also this could be the problem still i guess: [https://github.com/ProtocolSupport/ProtocolSupport/issues/1351#issuecomment-889748034](https://github.com/ProtocolSupport/ProtocolSupport/issues/1351#issuecomment-889748034)

**Comment by xknat** [comment]
@cmod31 does it work fine on spigot?

**Comment by vaporvee** [comment]
@xknat no its also a issue on spigot but to reproduce this issue it takes some time after starting the server like 5-10 minutes

**Comment by vaporvee** [comment]
and for some reason when deleting skinrestorer i still have my skin as a premium user. Fastlogin just forwards the premium uuid not the skin

**Comment by xknat** [comment]
> and for some reason when deleting skinrestorer i still have my skin as a premium user. Fastlogin just forwards the premium uuid not the skin

Can you try without any other plugin installed by sr and protocolsupport

**Comment by Swapneel665** [comment]
I also have the same issue pls find a fix for this

**Comment by xknat** [comment]
Unsupported version 14.1.1
We are now on 14.1.10
